export const INITIALIZE_IF_EMPTY = 'INITIALIZE_IF_EMPTY'

export const CARD_CREATED_TEXT = 'CARD_CREATED_TEXT'
export const CARD_CREATED_IMAGE = 'CARD_CREATED_IMAGE'

export const CARD_TEXT_CHANGED = 'CARD_TEXT_CHANGED'
export const CARD_TEXT_RESIZED = 'CARD_TEXT_RESIZED'

export const CARD_INLINED_IMAGE = 'CARD_INLINED_IMAGE'

export const CARD_MOVED = 'CARD_MOVED'
export const CARD_RESIZED = 'CARD_RESIZED'

export const CARD_SELECTED = 'CARD_SELECTED'
export const CARD_UNIQUELY_SELECTED = 'CARD_UNIQUELY_SELECTED'
export const CLEAR_SELECTIONS = 'CLEAR_SELECTIONS'

export const CARD_DELETED = 'CARD_DELETED'

export const DOCUMENT_READY = 'DOCUMENT_READY'
export const DOCUMENT_UPDATED = 'DOCUMENT_UPDATED'

export const FORM_CHANGED = 'FORM_CHANGED'
export const FORM_SUBMITTED = 'FORM_SUBMITTED'
