export const INITIALIZE_IF_EMPTY = 'INITIALIZE_IF_EMPTY'

export const CARD_CREATED_TEXT = 'CARD_CREATED_TEXT'
export const CARD_CREATED_IMAGE = 'CARD_CREATED_IMAGE'
export const CARD_CREATED_PDF = 'CARD_CREATED_PDF'

export const CARD_EDITOR_CHANGED = 'CARD_EDITOR_CHANGED'
export const CARD_TEXT_RESIZED = 'CARD_TEXT_RESIZED'

export const CARD_INLINED_IMAGE = 'CARD_INLINED_IMAGE'
export const CARD_INLINED_PDF = 'CARD_INLINED_PDF'

export const CARD_DRAG_STARTED = 'CARD_DRAG_STARTED'
export const CARD_DRAG_MOVED = 'CARD_DRAG_MOVED'
export const CARD_DRAG_STOPPED = 'CARD_DRAG_STOPPED'

export const CARD_SELECTED = 'CARD_SELECTED'
export const CARD_UNIQUELY_SELECTED = 'CARD_UNIQUELY_SELECTED'
export const CLEAR_SELECTIONS = 'CLEAR_SELECTIONS'

export const CARD_DELETED = 'CARD_DELETED'
